apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cpbxridvv-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/cpbxridvv-dotnet-basic-gitops